from PIL import Image
import numpy as np
from matplotlib.pyplot import imshow
from urllib.request import urlretrieve
import os
import datetime
import hashlib


class img_utils:

    def __init__(self, path):
        """
        Read in image bitmap and convert to array
        
        """
        self.path = path
        try:
            self.arr = self._read_image_local(self.path)
        except:
            self.arr = self._read_image_from_url()

    def _read_image_local(self, path):
        """
        Read image and store it as an array

        """
        if not os.path.exists('data'):
            os.makedirs('data')

        Image.open(path).save("data/img.bmp")
        img = Image.open("data/img.bmp")
        img_arr = np.array(img, dtype='int32')
        img.close()
        return img_arr

    def _read_image_from_url(self):
        """
        Read image from url and store it as an array

        """

        if not os.path.exists('data'):
            os.makedirs('data')

        fname = self._create_hashed_filename()

        urlretrieve(url= self.path, filename= fname)
        
        img_arr = self._read_image_local(path = fname)

        return img_arr

    def _create_hashed_filename(self):
        """
        Create a filename by hashing current time as string

        """

        time_str = str(datetime.datetime.now()).encode()
        hashed_obj = hashlib.md5(time_str)
        hashed_str = hashed_obj.hexdigest()
        ftype = self.path.split(".")[-1]
        fname = "data/" + hashed_str + "." + ftype

        return fname

    def display_image(self, img_array=None):
        """
        Display image

        """
        if img_array is None:
            self.arr = self.arr.astype(dtype='uint8')
            img = Image.fromarray(self.arr, 'RGB')
            imshow(np.asarray(img))
        else:
            arr = img_array.astype(dtype="uint8")
            arr = Image.fromarray(arr, 'RGB')
            imshow(np.asarray(arr))

    def reshape_img(self):
        """
        Takes in array generated by read_image function and converts to long format

        """
        long_array = np.reshape(self.arr, (self.arr.shape[0] * self.arr.shape[1], self.arr.shape[2]))
        self.long_array = long_array
        return long_array

    def rebuild_compressed_image(self, k_cluster_obj):
        """Takes k_cluster object and displays the compressed image"""
        
        centers = k_cluster_obj.current_centers_vect
        class_assignments = k_cluster_obj.group_assignment_vect
        original_array = self.arr

        centers_list = [x.tolist() for x in centers]
        class_assignment_list = [x for x in np.unique(class_assignments)]

        centroids_dict = {}
        for center,class_ in zip(centers_list,class_assignment_list):
            centroids_dict[class_] = center

        long_array = self.long_array
        compressed_array = np.array([[0,0,0]]*len(long_array))
        for ind, array_i in enumerate(zip(long_array, class_assignments)):
            x = array_i[1]
            compressed_array[ind] = centroids_dict[x]

        prime_shape = (original_array.shape[0],original_array.shape[1],original_array.shape[2])
        compressed_array_prime = np.reshape(compressed_array, prime_shape)

        self.display_image(compressed_array_prime)

